sonar.projectKey=mcp-fastapi
sonar.qualitygate.wait=true

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.host.url=https://sonar.pedroct.com.br